name: Sincronizar fork con el original

on:
  schedule:
    - cron: "0 */6 * * *" # cada 6 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    # Evita que se ejecute en el repositorio original si alguna vez se agrega ahí
    if: github.repository != 'marianoluzza/mision-software'
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el fork
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Sincronizar con el repositorio original
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898208+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/marianoluzza/mision-software.git
          git fetch upstream main
          git merge --no-edit upstream/main
          git push origin HEAD:main
